-- Ejecuta este script en SQL Editor de Supabase

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nombre text not null,
  tipo text not null,
  ciudad text,
  whatsapp text,
  mensaje text not null,
  user_id uuid references auth.users(id)
);

alter table public.leads enable row level security;

-- Usuarios autenticados pueden insertar y ver sus propios leads
drop policy if exists "insert own leads" on public.leads;
create policy "insert own leads"
on public.leads
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "select own leads" on public.leads;
create policy "select own leads"
on public.leads
for select
to authenticated
using (auth.uid() = user_id);

-- Permitir leads sin login (user_id null) para formulario publico
drop policy if exists "insert anonymous lead" on public.leads;
create policy "insert anonymous lead"
on public.leads
for insert
to anon
with check (user_id is null);
