-- Ejecuta este script en SQL Editor de Supabase

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nombre text not null,
  tipo text not null,
  ciudad text,
  whatsapp text,
  mensaje text not null,
  user_id uuid references auth.users(id)
);

alter table public.leads enable row level security;

-- Usuarios autenticados pueden insertar y ver sus propios leads
drop policy if exists "insert own leads" on public.leads;
create policy "insert own leads"
on public.leads
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "select own leads" on public.leads;
create policy "select own leads"
on public.leads
for select
to authenticated
using (auth.uid() = user_id);

-- Permitir leads sin login (user_id null) para formulario publico
drop policy if exists "insert anonymous lead" on public.leads;
create policy "insert anonymous lead"
on public.leads
for insert
to anon
with check (user_id is null);

-- Perfiles de usuario para referidos
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  full_name text,
  referral_code text not null unique,
  referred_by_code text references public.profiles(referral_code),
  referral_credits int not null default 0
);

alter table public.profiles enable row level security;

drop policy if exists "select profiles authenticated" on public.profiles;
create policy "select profiles authenticated"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "insert own profile" on public.profiles;
create policy "insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "update own profile" on public.profiles;
create policy "update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Relacion de referidos
create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  referrer_user_id uuid not null references auth.users(id) on delete cascade,
  referred_user_id uuid not null unique references auth.users(id) on delete cascade,
  referral_code text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected'))
);

alter table public.referrals enable row level security;

drop policy if exists "select own referrals" on public.referrals;
create policy "select own referrals"
on public.referrals
for select
to authenticated
using (auth.uid() = referrer_user_id or auth.uid() = referred_user_id);

drop policy if exists "insert own referred record" on public.referrals;
create policy "insert own referred record"
on public.referrals
for insert
to authenticated
with check (auth.uid() = referred_user_id);
